---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["curl", "wget", "apt-transport-https", "gnupg", "lsb-release"]
    state: latest
    update_cache: yes

- name: "add user to docker group"
  become: true
  shell: |
    groupadd docker
    usermod -aG docker $USER && newgrp docker

- name: "add docker official gpg key"
  become: true
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "install docker."
  become: yes
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    state: latest
    update_cache: yes

- name: "install minikube"
  become: true
  shell: |
    wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    cp minikube-linux-amd64 /usr/local/bin/minikube
    chmod +x /usr/local/bin/minikube

- name: "install kubectl"
  become: true
  shell: |
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl \
      -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl \
    chmod +x kubectl
    mv kubectl /usr/local/bin/

- name: "start minikube"
  shell: minikube start --driver=docker