---
- name: Run app
  shell: kubectl run todo-list-api --image=$DOCKER_IMAGE --port=3000 --labels app=todo
  environment:
    DOCKER_IMAGE: "{{ lookup('env','DOCKER_IMAGE') }}"

- name: Allow external traffic
  shell: |
    sleep 80
    sudo -E kubectl port-forward --address 0.0.0.0 todo-list-api 3000:3000 &