---
- name: Run app
  shell: kubectl run todo-list-api --image=$DOCKER_IMAGE --port=3000 --labels app=todo
  environment:
    DOCKER_IMAGE: "{{ lookup('env','DOCKER_IMAGE') }}"

- name: Allow external traffic
  shell: |
    sleep 45
    sudo -E kubectl port-forward todo-list-api 80:3000 &