---
- name: Run app
  shell: kubectl run todo-list-api --image=$DOCKER_IMAGE --port=3000 --labels app=todo
  environment:
    DOCKER_IMAGE: "{{ lookup('env','DOCKER_IMAGE') }}"

- name: Allow external traffic
  shell: |
    sudo -E kubectl port-forward todo-list-api 80:3000
  register: result
  until: result is succeeded
  ignore_errors: yes
  retries: 5
  delay: 30

- name: Report error
  fail:
    msg: '{{ result }}'
  when: result is not succeeded